export const BRANCH_LIST_REQUEST = "BRANCH_LIST_REQUEST";
export const BRANCH_LIST_SUCCESS = "BRANCH_LIST_SUCCESS";
export const BRANCH_LIST_FAIL = "BRANCH_LIST_FAIL";

export const BRANCH_DETAILS_REQUEST = "BRANCH_DETAILS_REQUEST";
export const BRANCH_DETAILS_SUCCESS = "BRANCH_DETAILS_SUCCESS";
export const BRANCH_DETAILS_FAIL = "BRANCH_DETAILS_FAIL";
