export const POST_LIST_REQUEST = "POST_LIST_REQUEST";
export const POST_LIST_SUCCESS = "POST_LIST_SUCCESS";
export const POST_LIST_FAIL = "POST_LIST_FAIL";

export const POST_ADD_REQUEST = "POST_ADD_REQUEST";
export const POST_ADD_SUCCESS = "POST_ADD_SUCCESS";
export const POST_ADD_FAIL = "POST_ADD_FAIL";

export const POST_DELETE_REQUEST = "POST_DELETE_REQUEST";
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";
export const POST_DELETE_FAIL = "POST_DELETE_FAIL";

export const POST_SINGLE_REQUEST = "POST_SINGLE_REQUEST";
export const POST_SINGLE_SUCCESS = "POST_SINGLE_SUCCESS";
export const POST_SINGLE_FAIL = "POST_SINGLE_FAIL";

export const REPLY_ADD_REQUEST = "REPLY_ADD_REQUEST";
export const REPLY_ADD_SUCCESS = "REPLY_ADD_SUCCESS";
export const REPLY_ADD_FAIL = "REPLY_ADD_FAIL";

export const REPLY_DELETE_REQUEST = "REPLY_DELETE_REQUEST";
export const REPLY_DELETE_SUCCESS = "REPLY_DELETE_SUCCESS";
export const REPLY_DELETE_FAIL = "REPLY_DELETE_FAIL";
