export const ISSUES_LIST_REQUEST = "ISSUES_LIST_REQUEST";
export const ISSUES_LIST_SUCCESS = "ISSUES_LIST_SUCCESS";
export const ISSUES_LIST_FAIL = "ISSUES_LIST_FAIL";

export const ISSUES_DELETE_REQUEST = "ISSUES_DELETE_REQUEST";
export const ISSUES_DELETE_SUCCESS = "ISSUES_DELETE_SUCCESS";
export const ISSUES_DELETE_FAIL = "ISSUES_DELETE_FAIL";
