export const NOTES_LIST_REQUEST = "NOTES_LIST_REQUEST";
export const NOTES_LIST_SUCCESS = "NOTES_LIST_SUCCESS";
export const NOTES_LIST_FAIL = "NOTES_LIST_FAIL";

export const PENDING_NOTES_LIST_REQUEST = "PENDING_NOTES_LIST_REQUEST";
export const PENDING_NOTES_LIST_SUCCESS = "PENDING_NOTES_LIST_SUCCESS";
export const PENDING_NOTES_LIST_FAIL = "PENDING_NOTES_LIST_FAIL";

export const PENDING_NOTES_APPROVE_SUCCESS = "PENDING_NOTES_APPROVE_SUCCESS";
export const PENDING_NOTES_APPROVE_FAIL = "PENDING_NOTES_APPROVE_FAIL";

export const PENDING_NOTES_DELETE_SUCCESS = "PENDING_NOTES_DELETE_SUCCESS";
export const PENDING_NOTES_DELETE_FAIL = "PENDING_NOTES_DELETE_FAIL";
